#ifndef COMMONPRINTDIALOG_GLOBAL_H
#define COMMONPRINTDIALOG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMONPRINTDIALOG_LIBRARY)
#  define COMMONPRINTDIALOGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMONPRINTDIALOGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMONPRINTDIALOG_GLOBAL_H
